//! Repo maintenance tasks. Currently: keep DOC.md's GraphQL schema section
//! in sync with the actual schema (`gen-docs`), checked in CI via `--check`.

use std::path::Path;

use async_graphql::{EmptySubscription, Schema};
use graphql_api::{MutationRoot, QueryRoot};

const START_MARKER: &str = "<!-- GRAPHQL_SCHEMA:START (auto-generated by `cargo run -p xtask -- gen-docs`, do not edit by hand) -->";
const END_MARKER: &str = "<!-- GRAPHQL_SCHEMA:END -->";
const DOC_PATH: &str = "DOC.md";

fn schema_sdl() -> String {
    Schema::build(QueryRoot, MutationRoot, EmptySubscription)
        .finish()
        .sdl()
}

fn splice(doc: &str, sdl: &str) -> Option<String> {
    let start = doc.find(START_MARKER)?;
    let end = doc.find(END_MARKER)?;
    if end < start {
        return None;
    }
    let before = &doc[..start + START_MARKER.len()];
    let after = &doc[end..];
    Some(format!("{before}\n\n```graphql\n{sdl}```\n\n{after}"))
}

fn main() {
    let mut args = std::env::args().skip(1);
    let cmd = args.next().unwrap_or_default();
    let check = args.any(|a| a == "--check");

    if cmd != "gen-docs" {
        eprintln!("usage: xtask gen-docs [--check]");
        std::process::exit(2);
    }

    let doc_path = Path::new(DOC_PATH);
    let doc = std::fs::read_to_string(doc_path)
        .unwrap_or_else(|e| panic!("failed to read {DOC_PATH}: {e}"));
    let sdl = schema_sdl();
    let updated = splice(&doc, &sdl).unwrap_or_else(|| {
        panic!(
            "{DOC_PATH} is missing the `{START_MARKER}` / `{END_MARKER}` markers"
        )
    });

    if check {
        if updated == doc {
            println!("{DOC_PATH} is in sync with the GraphQL schema.");
        } else {
            eprintln!(
                "{DOC_PATH}'s generated schema section is stale — run `cargo run -p xtask -- gen-docs` and commit the result."
            );
            std::process::exit(1);
        }
    } else {
        std::fs::write(doc_path, updated).unwrap_or_else(|e| panic!("failed to write {DOC_PATH}: {e}"));
        println!("{DOC_PATH} updated.");
    }
}
