//! Repo maintenance tasks. Currently: keep DOC.md's generated sections
//! (GraphQL schema, crate table, env var reference) in sync with the code,
//! checked in CI via `--check`. Run from the repo root.

use std::path::Path;

use async_graphql::{EmptySubscription, Schema};
use graphql_api::{MutationRoot, QueryRoot};

const DOC_PATH: &str = "DOC.md";
const ROOT_CARGO_TOML: &str = "Cargo.toml";
const CONFIG_RS: &str = "crates/server/src/config.rs";

fn marker(name: &str) -> (String, String) {
    (
        format!("<!-- {name}:START (auto-generated by `cargo run -p xtask -- gen-docs`, do not edit by hand) -->"),
        format!("<!-- {name}:END -->"),
    )
}

fn splice(doc: &str, name: &str, body: &str) -> String {
    let (start, end) = marker(name);
    let start_idx = doc
        .find(&start)
        .unwrap_or_else(|| panic!("{DOC_PATH} is missing the `{start}` marker"));
    let end_idx = doc
        .find(&end)
        .unwrap_or_else(|| panic!("{DOC_PATH} is missing the `{end}` marker"));
    assert!(end_idx >= start_idx, "{name} markers are out of order in {DOC_PATH}");
    let before = &doc[..start_idx + start.len()];
    let after = &doc[end_idx..];
    format!("{before}\n\n{body}\n\n{after}")
}

fn graphql_schema_section() -> String {
    let sdl = Schema::build(QueryRoot, MutationRoot, EmptySubscription)
        .finish()
        .sdl();
    format!("```graphql\n{sdl}```")
}

/// One row per workspace member, in `Cargo.toml`'s `[workspace] members`
/// order, sourced from each crate's own `[package] description`.
fn crates_table_section() -> String {
    let root: toml::Value = toml::from_str(
        &std::fs::read_to_string(ROOT_CARGO_TOML)
            .unwrap_or_else(|e| panic!("failed to read {ROOT_CARGO_TOML}: {e}")),
    )
    .unwrap_or_else(|e| panic!("failed to parse {ROOT_CARGO_TOML}: {e}"));

    let members = root["workspace"]["members"]
        .as_array()
        .expect("workspace.members should be an array");

    let mut out = String::from("| Crate | Responsibility |\n|---|---|\n");
    for m in members {
        let path = m.as_str().expect("member should be a string");
        let manifest_path = format!("{path}/Cargo.toml");
        let manifest: toml::Value = toml::from_str(
            &std::fs::read_to_string(&manifest_path)
                .unwrap_or_else(|e| panic!("failed to read {manifest_path}: {e}")),
        )
        .unwrap_or_else(|e| panic!("failed to parse {manifest_path}: {e}"));
        let name = manifest["package"]["name"].as_str().unwrap_or(path);
        let description = manifest["package"]["description"]
            .as_str()
            .unwrap_or("*(no `description` in this crate's Cargo.toml)*");
        out.push_str(&format!("| `{name}` | {description} |\n"));
    }
    out
}

/// Pairs each `pub field: Type` in `Config` (in declaration order) with the
/// `env::var("NAME")` call at the same position in `Config::from_env` (in
/// call order). This is a positional match, not a semantic one — it holds
/// today because both lists are written in the same order, but doesn't
/// verify field/var names correspond. If `config.rs` is restructured so the
/// two orderings diverge, this will silently mispair them.
/// ponytail: positional pairing, not name-verified — swap for a proper
/// `syn`-based parse (or a `#[env_var(...)]` attribute) if config.rs grows
/// enough fields that order drift becomes plausible.
fn env_vars_table_section() -> String {
    let src = std::fs::read_to_string(CONFIG_RS)
        .unwrap_or_else(|e| panic!("failed to read {CONFIG_RS}: {e}"));

    let struct_re = regex::Regex::new(r"(?s)pub struct Config \{(.*?)\n\}").unwrap();
    let struct_body = &struct_re
        .captures(&src)
        .unwrap_or_else(|| panic!("couldn't find `pub struct Config {{...}}` in {CONFIG_RS}"))[1];

    let field_re =
        regex::Regex::new(r"((?:[ \t]*///[^\n]*\n)*)[ \t]*pub (\w+): [^,\n]+,").unwrap();
    let mut fields = Vec::new();
    for cap in field_re.captures_iter(struct_body) {
        let doc: String = cap[1]
            .lines()
            .map(|l| l.trim().trim_start_matches("///").trim())
            .filter(|l| !l.is_empty())
            .collect::<Vec<_>>()
            .join(" ");
        fields.push((cap[2].to_string(), doc));
    }

    let var_re = regex::Regex::new(r#"env::var\("([A-Z0-9_]+)"\)([^;]*);"#).unwrap();
    let vars: Vec<(String, String)> = var_re
        .captures_iter(&src)
        .map(|c| (c[1].to_string(), c[2].to_string()))
        .collect();

    assert_eq!(
        fields.len(),
        vars.len(),
        "{CONFIG_RS}: found {} Config fields but {} env::var(...) calls in from_env() — \
         they're expected to correspond 1:1 in declaration order; xtask's positional \
         pairing needs updating if that's no longer true.",
        fields.len(),
        vars.len()
    );

    let default_re = regex::Regex::new(r#"\.unwrap_or(?:_else\(\|_\| )?\(?"([^"]*)""#).unwrap();

    let mut out = String::from("| Variable | Default | Purpose |\n|---|---|---|\n");
    for ((_field, doc), (var, rest)) in fields.iter().zip(vars.iter()) {
        let default = if rest.contains(".context(") {
            "*(required)*".to_string()
        } else if let Some(d) = default_re.captures(rest) {
            format!("`{}`", &d[1])
        } else if rest.trim().ends_with(".ok()") {
            "*(unset)*".to_string()
        } else {
            "*(computed — see source)*".to_string()
        };
        let purpose = if doc.is_empty() {
            "*(undocumented — add a `///` doc comment on this field in `config.rs`)*".to_string()
        } else {
            doc.clone()
        };
        out.push_str(&format!("| `{var}` | {default} | {purpose} |\n"));
    }
    out
}

fn main() {
    let mut args = std::env::args().skip(1);
    let cmd = args.next().unwrap_or_default();
    let check = args.any(|a| a == "--check");

    if cmd != "gen-docs" {
        eprintln!("usage: xtask gen-docs [--check]");
        std::process::exit(2);
    }

    let doc_path = Path::new(DOC_PATH);
    let original = std::fs::read_to_string(doc_path)
        .unwrap_or_else(|e| panic!("failed to read {DOC_PATH}: {e}"));

    let mut updated = original.clone();
    updated = splice(&updated, "GRAPHQL_SCHEMA", &graphql_schema_section());
    updated = splice(&updated, "CRATES_TABLE", &crates_table_section());
    updated = splice(&updated, "ENV_VARS_TABLE", &env_vars_table_section());

    if check {
        if updated == original {
            println!("{DOC_PATH} is in sync with the code.");
        } else {
            eprintln!(
                "{DOC_PATH}'s generated sections are stale — run `cargo run -p xtask -- gen-docs` and commit the result."
            );
            std::process::exit(1);
        }
    } else {
        std::fs::write(doc_path, updated).unwrap_or_else(|e| panic!("failed to write {DOC_PATH}: {e}"));
        println!("{DOC_PATH} updated.");
    }
}
