use std::path::{Path, PathBuf};

use chrono::{TimeZone, Utc};
use git2::{ObjectType, Repository};

use crate::error::{GitCoreError, Result};
use crate::types::{CommitInfo, EntryKind, TreeEntry};
use crate::validate::validate_slug;

/// Manages the on-disk layout of bare git repositories, storing each
/// repository at `{root}/{owner}/{repo_name}.git`.
#[derive(Debug, Clone)]
pub struct RepoManager {
    root: PathBuf,
}

impl RepoManager {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Compute the filesystem path for a repository without touching disk.
    pub fn repo_path(&self, owner: &str, name: &str) -> Result<PathBuf> {
        validate_slug(owner)?;
        validate_slug(name)?;
        Ok(self.root.join(owner).join(format!("{name}.git")))
    }

    /// Initialize a new bare repository at `{root}/{owner}/{name}.git`.
    pub fn init_repo(&self, owner: &str, name: &str) -> Result<PathBuf> {
        let path = self.repo_path(owner, name)?;
        if path.exists() {
            return Err(GitCoreError::RepoAlreadyExists(path));
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        Repository::init_bare(&path)?;
        Self::write_pre_receive_hook(&path, owner, name)?;
        Ok(path)
    }

    /// Write a `hooks/pre-receive` script into a freshly-initialized bare
    /// repo. Git invokes this hook (if present and executable) *before* any
    /// ref is updated, feeding it `<old-sha> <new-sha> <ref-name>\n` lines on
    /// stdin for every ref the push touches. Exiting non-zero here causes git
    /// to abort the entire push -- no refs are updated -- which is the only
    /// correct place to truly block a force-push to a protected branch
    /// (unlike a post-receive check, which runs after git has already
    /// accepted the push).
    ///
    /// The script just re-invokes this same server binary with a small
    /// `check-push-protection` subcommand (see `crates/server/src/main.rs`),
    /// which reads the same `<old> <new> <ref>` stdin lines, consults the
    /// `branch_protection_rules` table, and exits non-zero if a protected
    /// branch would be force-pushed.
    ///
    /// NOTE (Windows dev vs. Linux prod): git for Windows (msys) does honor
    /// a `#!/bin/sh` shebang line for hook scripts even without a POSIX
    /// executable bit, so this works for local Windows development too. On
    /// real (Linux) deployments the file must be `chmod +x`, which we do
    /// here when compiled for unix; on Windows there is no executable bit to
    /// set, so that step is skipped (no-op).
    ///
    /// SCOPE NOTE: this hook is only written when a repo is *newly created*
    /// via `init_repo`. Repositories that already existed before this change
    /// shipped will not have the hook and must have it backfilled manually
    /// (e.g. a one-off maintenance script that re-runs this same write for
    /// every existing bare repo under `root`) -- that backfill is out of
    /// scope here.
    fn write_pre_receive_hook(repo_path: &Path, owner: &str, name: &str) -> Result<()> {
        let current_exe = std::env::current_exe().map_err(GitCoreError::Io)?;
        // The hook runs with a cwd controlled by git (typically the repo dir
        // itself, sometimes different depending on transport), so a relative
        // `repo_path` embedded in the script would resolve against the wrong
        // directory. Canonicalize to an absolute path at write time.
        let absolute_repo_path = repo_path
            .canonicalize()
            .map(|p| {
                // On Windows, `canonicalize()` returns a `\\?\`-prefixed verbatim
                // path, which git-for-windows' MSYS `/bin/sh` and git2 don't
                // reliably handle. Strip the prefix; the remaining path is
                // still absolute.
                let s = p.to_string_lossy().to_string();
                let stripped = s.strip_prefix(r"\\?\").map(String::from).unwrap_or(s);
                PathBuf::from(stripped)
            })
            .unwrap_or_else(|_| repo_path.to_path_buf());
        let exe_display = current_exe.to_string_lossy().replace('"', "\\\"");
        let repo_display = absolute_repo_path.to_string_lossy().replace('"', "\\\"");

        let script = format!(
            "#!/bin/sh\n\
             # Auto-generated by RepoManager::init_repo -- do not edit by hand.\n\
             # Delegates the real accept/reject decision to the server binary.\n\
             exec \"{exe}\" check-push-protection --repo-path \"{repo}\" --owner \"{owner}\" --name \"{name}\"\n",
            exe = exe_display,
            repo = repo_display,
            owner = owner,
            name = name,
        );

        let hooks_dir = repo_path.join("hooks");
        std::fs::create_dir_all(&hooks_dir)?;
        let hook_path = hooks_dir.join("pre-receive");
        std::fs::write(&hook_path, script)?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&hook_path)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&hook_path, perms)?;
        }

        Ok(())
    }

    /// Compute the filesystem path for a repository's wiki (a second bare
    /// repo, named `{name}.wiki.git`, mirroring Forgejo's wiki model).
    pub fn wiki_repo_path(&self, owner: &str, name: &str) -> PathBuf {
        // Best-effort slug validation; callers are expected to have already
        // validated owner/name via `repo_path`/`init_repo` on the main repo.
        self.root.join(owner).join(format!("{name}.wiki.git"))
    }

    /// Initialize a new bare wiki repository at `{root}/{owner}/{name}.wiki.git`.
    pub fn init_wiki(&self, owner: &str, name: &str) -> Result<PathBuf> {
        validate_slug(owner)?;
        validate_slug(name)?;
        let path = self.wiki_repo_path(owner, name);
        if path.exists() {
            return Err(GitCoreError::RepoAlreadyExists(path));
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        Repository::init_bare(&path)?;
        Ok(path)
    }

    fn open_wiki(&self, owner: &str, name: &str) -> Result<(Repository, PathBuf)> {
        validate_slug(owner)?;
        validate_slug(name)?;
        let path = self.wiki_repo_path(owner, name);
        if !path.exists() {
            return Err(GitCoreError::RepoNotFound(path));
        }
        let repo = Repository::open_bare(&path)?;
        Ok((repo, path))
    }

    /// List the `.md` page names (without extension) present at HEAD of the
    /// wiki repository's default branch.
    pub fn wiki_list_pages(&self, owner: &str, name: &str) -> Result<Vec<String>> {
        let (repo, _) = self.open_wiki(owner, name)?;
        let head = match repo.head() {
            Ok(head) => head,
            Err(_) => return Ok(Vec::new()), // unborn repo: no pages yet
        };
        let commit = head
            .peel_to_commit()
            .map_err(|_| GitCoreError::NoDefaultBranch)?;
        let tree = commit.tree()?;

        let mut out = Vec::new();
        for entry in tree.iter() {
            if entry.kind() != Some(ObjectType::Blob) {
                continue;
            }
            let entry_name = entry.name().unwrap_or_default();
            if let Some(page) = entry_name.strip_suffix(".md") {
                out.push(page.to_string());
            }
        }
        Ok(out)
    }

    /// Read the content of `{page}.md` at HEAD of the wiki repository as a
    /// UTF-8 string.
    pub fn wiki_read_page(&self, owner: &str, name: &str, page: &str) -> Result<String> {
        let (repo, _) = self.open_wiki(owner, name)?;
        let head = repo.head().map_err(|_| {
            GitCoreError::PathNotFound(format!("{page}.md"))
        })?;
        let commit = head
            .peel_to_commit()
            .map_err(|_| GitCoreError::PathNotFound(format!("{page}.md")))?;
        let tree = commit.tree()?;
        let file_path = format!("{page}.md");
        let entry = tree
            .get_path(Path::new(&file_path))
            .map_err(|_| GitCoreError::PathNotFound(file_path.clone()))?;
        let object = entry.to_object(&repo)?;
        let blob = object
            .as_blob()
            .ok_or_else(|| GitCoreError::NotAFile(file_path.clone()))?;
        Ok(String::from_utf8(blob.content().to_vec())?)
    }

    /// Create or update `{page}.md` in the wiki repository, committing the
    /// change on the default branch (creating it, as "master", if the repo
    /// is unborn). Returns the new commit's sha.
    #[allow(clippy::too_many_arguments)]
    pub fn wiki_write_page(
        &self,
        owner: &str,
        name: &str,
        page: &str,
        content: &str,
        author_name: &str,
        author_email: &str,
        message: &str,
    ) -> Result<String> {
        let (repo, _) = self.open_wiki(owner, name)?;
        const WIKI_DEFAULT_BRANCH: &str = "master";
        let ref_name = format!("refs/heads/{WIKI_DEFAULT_BRANCH}");

        let (parent_commit, base_tree) = match repo.head() {
            Ok(head) => {
                let commit = head.peel_to_commit()?;
                let tree = commit.tree()?;
                (Some(commit), Some(tree))
            }
            Err(_) => (None, None),
        };

        let blob_oid = repo.blob(content.as_bytes())?;

        let mut builder = repo.treebuilder(base_tree.as_ref())?;
        let file_name = format!("{page}.md");
        builder.insert(&file_name, blob_oid, 0o100644)?;
        let tree_oid = builder.write()?;
        let tree = repo.find_tree(tree_oid)?;

        let signature = git2::Signature::now(author_name, author_email)?;

        let parents: Vec<&git2::Commit> = parent_commit.iter().collect();
        let commit_oid = repo.commit(
            Some(&ref_name),
            &signature,
            &signature,
            message,
            &tree,
            &parents,
        )?;

        // If the repo was unborn (no HEAD ref existed), point HEAD at the
        // newly created branch.
        if repo.head().is_err() {
            repo.set_head(&ref_name)?;
        }

        Ok(commit_oid.to_string())
    }

    /// Permanently delete a repository from disk.
    pub fn delete_repo(&self, owner: &str, name: &str) -> Result<()> {
        let path = self.repo_path(owner, name)?;
        if !path.exists() {
            return Err(GitCoreError::RepoNotFound(path));
        }
        std::fs::remove_dir_all(&path)?;
        Ok(())
    }

    fn open(&self, owner: &str, name: &str) -> Result<(Repository, PathBuf)> {
        let path = self.repo_path(owner, name)?;
        if !path.exists() {
            return Err(GitCoreError::RepoNotFound(path));
        }
        let repo = Repository::open_bare(&path)?;
        Ok((repo, path))
    }

    /// Determine whether `ancestor_sha` is an ancestor of (or equal to)
    /// `descendant_sha`. Used to detect non-fast-forward ("force") pushes: a
    /// push that moves a branch ref to a commit that is *not* a descendant
    /// of the previous tip is a force push (history was rewritten).
    pub fn is_ancestor(
        &self,
        owner: &str,
        name: &str,
        ancestor_sha: &str,
        descendant_sha: &str,
    ) -> Result<bool> {
        let (repo, _) = self.open(owner, name)?;
        // When this runs from a `pre-receive` hook, the newly-pushed objects
        // haven't been migrated into the repo's main object store yet --
        // git keeps them in a temporary "quarantine" object directory
        // (exposed via GIT_OBJECT_DIRECTORY / GIT_ALTERNATE_OBJECT_DIRECTORIES
        // env vars, which git sets for hook subprocesses) until the push is
        // fully accepted. Register those as odb alternates so lookups here
        // can actually see the new commit.
        if let Ok(quarantine_dir) = std::env::var("GIT_OBJECT_DIRECTORY") {
            let _ = repo.odb()?.add_disk_alternate(&quarantine_dir);
        }
        if let Ok(alternates) = std::env::var("GIT_ALTERNATE_OBJECT_DIRECTORIES") {
            let sep = if cfg!(windows) { ';' } else { ':' };
            for path in alternates.split(sep) {
                if !path.is_empty() {
                    let _ = repo.odb()?.add_disk_alternate(path);
                }
            }
        }
        let ancestor_oid = git2::Oid::from_str(ancestor_sha)
            .map_err(|_| GitCoreError::RefNotFound(ancestor_sha.to_string()))?;
        let descendant_oid = git2::Oid::from_str(descendant_sha)
            .map_err(|_| GitCoreError::RefNotFound(descendant_sha.to_string()))?;
        if ancestor_oid == descendant_oid {
            return Ok(true);
        }
        Ok(repo.graph_descendant_of(descendant_oid, ancestor_oid)?)
    }

    /// List local branch names for a repository.
    pub fn list_branches(&self, owner: &str, name: &str) -> Result<Vec<String>> {
        let (repo, _) = self.open(owner, name)?;
        let mut out = Vec::new();
        for branch in repo.branches(Some(git2::BranchType::Local))? {
            let (branch, _) = branch?;
            if let Some(branch_name) = branch.name()? {
                out.push(branch_name.to_string());
            }
        }
        Ok(out)
    }

    /// List tag names for a repository.
    pub fn list_tags(&self, owner: &str, name: &str) -> Result<Vec<String>> {
        let (repo, _) = self.open(owner, name)?;
        let tag_names = repo.tag_names(None)?;
        Ok(tag_names.iter().flatten().map(|s| s.to_string()).collect())
    }

    /// Determine the default branch: prefer HEAD's target, falling back to
    /// `main` or `master` if present.
    pub fn get_default_branch(&self, owner: &str, name: &str) -> Result<String> {
        let (repo, _) = self.open(owner, name)?;
        if let Ok(head) = repo.head() {
            if let Some(shorthand) = head.shorthand() {
                return Ok(shorthand.to_string());
            }
        }
        for candidate in ["main", "master"] {
            if repo
                .find_branch(candidate, git2::BranchType::Local)
                .is_ok()
            {
                return Ok(candidate.to_string());
            }
        }
        Err(GitCoreError::NoDefaultBranch)
    }

    /// Resolve a ref-like string (branch, tag, or sha) to a commit.
    fn resolve_commit<'repo>(
        &self,
        repo: &'repo Repository,
        rev: &str,
    ) -> Result<git2::Commit<'repo>> {
        let obj = repo
            .revparse_single(rev)
            .map_err(|_| GitCoreError::RefNotFound(rev.to_string()))?;
        let commit = obj
            .peel_to_commit()
            .map_err(|_| GitCoreError::RefNotFound(rev.to_string()))?;
        Ok(commit)
    }

    /// Read the raw bytes of a file at a given ref and path.
    pub fn read_file_at_ref(
        &self,
        owner: &str,
        name: &str,
        rev: &str,
        path: &str,
    ) -> Result<Vec<u8>> {
        let (repo, _) = self.open(owner, name)?;
        let commit = self.resolve_commit(&repo, rev)?;
        let tree = commit.tree()?;
        let entry = tree
            .get_path(Path::new(path))
            .map_err(|_| GitCoreError::PathNotFound(path.to_string()))?;
        let object = entry.to_object(&repo)?;
        let blob = object
            .as_blob()
            .ok_or_else(|| GitCoreError::NotAFile(path.to_string()))?;
        Ok(blob.content().to_vec())
    }

    /// List the entries of a directory tree at a given ref and path.
    /// Pass an empty string or "/" for `path` to list the tree root.
    pub fn list_tree(
        &self,
        owner: &str,
        name: &str,
        rev: &str,
        path: &str,
    ) -> Result<Vec<TreeEntry>> {
        let (repo, _) = self.open(owner, name)?;
        let commit = self.resolve_commit(&repo, rev)?;
        let root_tree = commit.tree()?;

        let target_tree = if path.is_empty() || path == "/" {
            root_tree
        } else {
            let entry = root_tree
                .get_path(Path::new(path))
                .map_err(|_| GitCoreError::PathNotFound(path.to_string()))?;
            let object = entry.to_object(&repo)?;
            object
                .as_tree()
                .cloned()
                .ok_or_else(|| GitCoreError::PathNotFound(path.to_string()))?
        };

        let base = if path.is_empty() || path == "/" {
            String::new()
        } else {
            format!("{}/", path.trim_matches('/'))
        };

        let mut out = Vec::new();
        for entry in target_tree.iter() {
            let entry_name = entry.name().unwrap_or_default().to_string();
            let full_path = format!("{base}{entry_name}");
            let oid = entry.id().to_string();
            match entry.kind() {
                Some(ObjectType::Tree) => {
                    out.push(TreeEntry {
                        name: entry_name,
                        path: full_path,
                        kind: EntryKind::Tree,
                        size: None,
                        oid,
                    });
                }
                Some(ObjectType::Blob) => {
                    let size = repo
                        .find_blob(entry.id())
                        .ok()
                        .map(|blob| blob.size() as u64);
                    out.push(TreeEntry {
                        name: entry_name,
                        path: full_path,
                        kind: EntryKind::Blob,
                        size,
                        oid,
                    });
                }
                _ => {}
            }
        }
        Ok(out)
    }

    /// Walk the commit history starting at `rev`, returning up to `limit`
    /// commits (most recent first).
    pub fn commit_log(
        &self,
        owner: &str,
        name: &str,
        rev: &str,
        limit: usize,
    ) -> Result<Vec<CommitInfo>> {
        let (repo, _) = self.open(owner, name)?;
        let start = self.resolve_commit(&repo, rev)?;

        let mut revwalk = repo.revwalk()?;
        revwalk.push(start.id())?;
        revwalk.set_sorting(git2::Sort::TOPOLOGICAL | git2::Sort::TIME)?;

        let mut out = Vec::new();
        for oid in revwalk {
            if out.len() >= limit {
                break;
            }
            let oid = oid?;
            let commit = repo.find_commit(oid)?;
            let author = commit.author();
            let timestamp = Utc
                .timestamp_opt(commit.time().seconds(), 0)
                .single()
                .unwrap_or_else(Utc::now);
            out.push(CommitInfo {
                sha: commit.id().to_string(),
                author_name: author.name().unwrap_or_default().to_string(),
                author_email: author.email().unwrap_or_default().to_string(),
                message: commit.message().unwrap_or_default().to_string(),
                timestamp,
            });
        }
        Ok(out)
    }

    /// Produce a unified diff (text) between a commit and its first parent
    /// (or against an empty tree if it is a root commit).
    pub fn get_commit_diff(&self, owner: &str, name: &str, sha: &str) -> Result<String> {
        let (repo, _) = self.open(owner, name)?;
        let commit = self.resolve_commit(&repo, sha)?;
        let new_tree = commit.tree()?;
        let old_tree = if commit.parent_count() > 0 {
            Some(commit.parent(0)?.tree()?)
        } else {
            None
        };

        let mut opts = git2::DiffOptions::new();
        let diff = repo.diff_tree_to_tree(old_tree.as_ref(), Some(&new_tree), Some(&mut opts))?;

        let mut buf = Vec::new();
        diff.print(git2::DiffFormat::Patch, |_delta, _hunk, line| {
            match line.origin() {
                '+' | '-' | ' ' => buf.push(line.origin() as u8),
                _ => {}
            }
            buf.extend_from_slice(line.content());
            true
        })?;

        Ok(String::from_utf8(buf)?)
    }

    /// Produce an in-memory tar archive of the full tree at `git_ref`,
    /// recursively including every blob with its original file mode.
    pub fn archive_tree_at_ref(&self, owner: &str, name: &str, git_ref: &str) -> Result<Vec<u8>> {
        let (repo, _) = self.open(owner, name)?;
        let commit = self.resolve_commit(&repo, git_ref)?;
        let tree = commit.tree()?;

        let mut builder = tar::Builder::new(Vec::new());
        Self::write_tree_to_tar(&repo, &tree, "", &mut builder)?;

        let data = builder.into_inner()?;
        Ok(data)
    }

    /// Merge `source_branch` into `target_branch`. If the target is already
    /// up-to-date with the source, this is a no-op and returns the target's
    /// current commit sha. If a fast-forward is possible, the target branch
    /// ref is simply moved to the source's commit. Otherwise a real merge
    /// commit is created with both branch tips as parents. Returns the sha
    /// of the resulting commit (as hex string).
    #[allow(clippy::too_many_arguments)]
    pub fn merge_branches(
        &self,
        owner: &str,
        name: &str,
        source_branch: &str,
        target_branch: &str,
        author_name: &str,
        author_email: &str,
        message: &str,
    ) -> Result<String> {
        let (repo, _) = self.open(owner, name)?;

        let source_commit = self.resolve_commit(&repo, source_branch)?;
        let target_commit = self.resolve_commit(&repo, target_branch)?;

        let target_ref_name = format!("refs/heads/{target_branch}");

        // `merge_analysis` operates against the repo's current HEAD, which
        // isn't necessarily `target_branch`, so determine fast-forward /
        // up-to-date status directly via ancestry checks instead.
        if source_commit.id() == target_commit.id()
            || repo.graph_descendant_of(target_commit.id(), source_commit.id())?
        {
            // Target already contains source's history: no-op.
            return Ok(target_commit.id().to_string());
        }

        if repo.graph_descendant_of(source_commit.id(), target_commit.id())? {
            // Source is strictly ahead of target: fast-forward.
            let mut target_ref = repo.find_reference(&target_ref_name)?;
            target_ref.set_target(source_commit.id(), "fast-forward merge")?;
            return Ok(source_commit.id().to_string());
        }

        // Real merge commit.
        let base_oid = repo.merge_base(target_commit.id(), source_commit.id())?;
        let base_commit = repo.find_commit(base_oid)?;

        let ancestor_tree = base_commit.tree()?;
        let target_tree = target_commit.tree()?;
        let source_tree = source_commit.tree()?;

        let mut index = repo.merge_trees(&ancestor_tree, &target_tree, &source_tree, None)?;

        if index.has_conflicts() {
            return Err(GitCoreError::MergeConflict(
                source_branch.to_string(),
                target_branch.to_string(),
            ));
        }

        let tree_oid = index.write_tree_to(&repo)?;
        let tree = repo.find_tree(tree_oid)?;

        let signature = git2::Signature::now(author_name, author_email)?;

        let commit_oid = repo.commit(
            Some(&target_ref_name),
            &signature,
            &signature,
            message,
            &tree,
            &[&target_commit, &source_commit],
        )?;

        Ok(commit_oid.to_string())
    }

    /// Squash-merge `source_branch` into `target_branch`: computes the same
    /// merged tree as `merge_branches`'s 3-way logic, but creates a single
    /// -parent commit on top of `target_branch`'s current tip instead of a
    /// 2-parent merge commit. Returns the new commit's sha (as hex string).
    #[allow(clippy::too_many_arguments)]
    pub fn squash_merge(
        &self,
        owner: &str,
        name: &str,
        source_branch: &str,
        target_branch: &str,
        author_name: &str,
        author_email: &str,
        message: &str,
    ) -> Result<String> {
        let (repo, _) = self.open(owner, name)?;

        let source_commit = self.resolve_commit(&repo, source_branch)?;
        let target_commit = self.resolve_commit(&repo, target_branch)?;

        let target_ref_name = format!("refs/heads/{target_branch}");

        let base_oid = repo.merge_base(target_commit.id(), source_commit.id())?;
        let base_commit = repo.find_commit(base_oid)?;

        let ancestor_tree = base_commit.tree()?;
        let target_tree = target_commit.tree()?;
        let source_tree = source_commit.tree()?;

        let mut index = repo.merge_trees(&ancestor_tree, &target_tree, &source_tree, None)?;

        if index.has_conflicts() {
            return Err(GitCoreError::MergeConflict(
                source_branch.to_string(),
                target_branch.to_string(),
            ));
        }

        let tree_oid = index.write_tree_to(&repo)?;
        let tree = repo.find_tree(tree_oid)?;

        let signature = git2::Signature::now(author_name, author_email)?;

        let commit_oid = repo.commit(
            Some(&target_ref_name),
            &signature,
            &signature,
            message,
            &tree,
            &[&target_commit],
        )?;

        Ok(commit_oid.to_string())
    }

    /// Rebase-merge `source_branch` onto `target_branch`: replays each
    /// commit unique to `source_branch` (found via a revwalk that hides
    /// everything reachable from `target_branch`) one at a time on top of
    /// `target_branch`'s current tip, in oldest-first order. Updates the
    /// target branch ref to the final replayed commit. Returns its sha (as
    /// hex string).
    #[allow(clippy::too_many_arguments)]
    pub fn rebase_merge(
        &self,
        owner: &str,
        name: &str,
        source_branch: &str,
        target_branch: &str,
        author_name: &str,
        author_email: &str,
    ) -> Result<String> {
        let (repo, _) = self.open(owner, name)?;

        let source_commit = self.resolve_commit(&repo, source_branch)?;
        let target_commit = self.resolve_commit(&repo, target_branch)?;

        let target_ref_name = format!("refs/heads/{target_branch}");

        let mut revwalk = repo.revwalk()?;
        revwalk.push(source_commit.id())?;
        revwalk.hide(target_commit.id())?;
        revwalk.set_sorting(git2::Sort::TOPOLOGICAL | git2::Sort::REVERSE)?;

        let commit_oids: Vec<git2::Oid> = revwalk.collect::<std::result::Result<_, _>>()?;

        let signature = git2::Signature::now(author_name, author_email)?;
        let mut new_base_commit = target_commit;

        for oid in commit_oids {
            let source_commit = repo.find_commit(oid)?;

            let mut index = repo.cherrypick_commit(&source_commit, &new_base_commit, 0, None)?;
            if index.has_conflicts() {
                return Err(GitCoreError::MergeConflict(
                    source_branch.to_string(),
                    target_branch.to_string(),
                ));
            }

            let tree_oid = index.write_tree_to(&repo)?;
            let tree = repo.find_tree(tree_oid)?;

            let commit_oid = repo.commit(
                None,
                &signature,
                &signature,
                source_commit.message().unwrap_or_default(),
                &tree,
                &[&new_base_commit],
            )?;
            new_base_commit = repo.find_commit(commit_oid)?;
        }

        let mut target_ref = repo.find_reference(&target_ref_name)?;
        target_ref.set_target(new_base_commit.id(), "rebase merge")?;

        Ok(new_base_commit.id().to_string())
    }

    /// Bare-clone the source repository into the destination path (used for
    /// repository forks).
    pub fn fork_repo(
        &self,
        source_owner: &str,
        source_name: &str,
        dest_owner: &str,
        dest_name: &str,
    ) -> Result<()> {
        let (_repo, source_path) = self.open(source_owner, source_name)?;
        let dest_path = self.repo_path(dest_owner, dest_name)?;
        if dest_path.exists() {
            return Err(GitCoreError::RepoAlreadyExists(dest_path));
        }
        if let Some(parent) = dest_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        git2::build::RepoBuilder::new()
            .bare(true)
            .clone(&source_path.to_string_lossy(), &dest_path)?;
        Ok(())
    }

    /// Recursively walk `tree`, appending every blob it (transitively)
    /// contains to `builder` as a tar entry under `prefix`.
    fn write_tree_to_tar(
        repo: &Repository,
        tree: &git2::Tree,
        prefix: &str,
        builder: &mut tar::Builder<Vec<u8>>,
    ) -> Result<()> {
        for entry in tree.iter() {
            let entry_name = entry.name().unwrap_or_default().to_string();
            let full_path = format!("{prefix}{entry_name}");
            match entry.kind() {
                Some(ObjectType::Tree) => {
                    let object = entry.to_object(repo)?;
                    let subtree = object
                        .as_tree()
                        .ok_or_else(|| GitCoreError::PathNotFound(full_path.clone()))?;
                    Self::write_tree_to_tar(repo, subtree, &format!("{full_path}/"), builder)?;
                }
                Some(ObjectType::Blob) => {
                    let object = entry.to_object(repo)?;
                    let blob = object
                        .as_blob()
                        .ok_or_else(|| GitCoreError::NotAFile(full_path.clone()))?;
                    let mode = entry.filemode() as u32;
                    let mut header = tar::Header::new_gnu();
                    header.set_size(blob.content().len() as u64);
                    header.set_mode(mode);
                    header.set_cksum();
                    builder.append_data(&mut header, &full_path, blob.content())?;
                }
                _ => {}
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read as _;

    /// Create a fresh `RepoManager` rooted at a temp dir, plus a bare repo
    /// under it with a single commit containing one file.
    fn setup_repo_with_commit() -> (tempfile::TempDir, RepoManager, String) {
        let dir = tempfile::tempdir().expect("tempdir");
        let manager = RepoManager::new(dir.path());
        manager.init_repo("acme", "widgets").expect("init repo");
        let repo_path = manager.repo_path("acme", "widgets").expect("repo path");
        let repo = Repository::open_bare(&repo_path).expect("open bare repo");

        let mut index = repo.index().expect("index");
        let blob_oid = repo
            .blob(b"hello from archive test\n")
            .expect("write blob");
        index
            .add(&git2::IndexEntry {
                ctime: git2::IndexTime::new(0, 0),
                mtime: git2::IndexTime::new(0, 0),
                dev: 0,
                ino: 0,
                mode: 0o100644,
                uid: 0,
                gid: 0,
                file_size: 24,
                id: blob_oid,
                flags: 0,
                flags_extended: 0,
                path: b"hello.txt".to_vec(),
            })
            .expect("add index entry");
        let tree_oid = index.write_tree_to(&repo).expect("write tree");
        let tree = repo.find_tree(tree_oid).expect("find tree");
        let sig = git2::Signature::now("Test", "test@example.com").expect("signature");
        let commit_oid = repo
            .commit(Some("HEAD"), &sig, &sig, "initial commit", &tree, &[])
            .expect("commit");

        (dir, manager, commit_oid.to_string())
    }

    #[test]
    fn archive_tree_at_ref_produces_expected_tar() {
        let (_dir, manager, commit_sha) = setup_repo_with_commit();

        let archive_bytes = manager
            .archive_tree_at_ref("acme", "widgets", &commit_sha)
            .expect("archive tree");

        let mut archive = tar::Archive::new(archive_bytes.as_slice());
        let entries = archive.entries().expect("entries");

        let mut found = false;
        for entry in entries {
            let mut entry = entry.expect("entry");
            let path = entry.path().expect("path").to_string_lossy().to_string();
            if path == "hello.txt" {
                let mut contents = String::new();
                entry.read_to_string(&mut contents).expect("read entry");
                assert_eq!(contents, "hello from archive test\n");
                found = true;
            }
        }
        assert!(found, "expected hello.txt entry in tar archive");
    }

    /// Commit a single file with given content on top of `parent_oid` (or
    /// as a root commit if `parent_oid` is `None`), updating the given ref.
    fn commit_file(
        repo: &Repository,
        ref_name: &str,
        parent_oid: Option<git2::Oid>,
        file_name: &str,
        content: &[u8],
    ) -> git2::Oid {
        let mut index = git2::Index::new().expect("new index");
        if let Some(parent) = parent_oid {
            let parent_commit = repo.find_commit(parent).expect("find parent");
            index
                .read_tree(&parent_commit.tree().expect("parent tree"))
                .expect("read tree into index");
        }
        let blob_oid = repo.blob(content).expect("write blob");
        index
            .add(&git2::IndexEntry {
                ctime: git2::IndexTime::new(0, 0),
                mtime: git2::IndexTime::new(0, 0),
                dev: 0,
                ino: 0,
                mode: 0o100644,
                uid: 0,
                gid: 0,
                file_size: content.len() as u32,
                id: blob_oid,
                flags: 0,
                flags_extended: 0,
                path: file_name.as_bytes().to_vec(),
            })
            .expect("add index entry");
        let tree_oid = index.write_tree_to(repo).expect("write tree");
        let tree = repo.find_tree(tree_oid).expect("find tree");
        let sig = git2::Signature::now("Test", "test@example.com").expect("signature");
        let parents: Vec<git2::Commit> = parent_oid
            .map(|oid| vec![repo.find_commit(oid).expect("find parent")])
            .unwrap_or_default();
        let parent_refs: Vec<&git2::Commit> = parents.iter().collect();
        repo.commit(Some(ref_name), &sig, &sig, "commit", &tree, &parent_refs)
            .expect("commit")
    }

    #[test]
    fn merge_branches_fast_forwards_when_possible() {
        let dir = tempfile::tempdir().expect("tempdir");
        let manager = RepoManager::new(dir.path());
        manager.init_repo("acme", "widgets").expect("init repo");
        let repo_path = manager.repo_path("acme", "widgets").expect("repo path");
        let repo = Repository::open_bare(&repo_path).expect("open bare repo");

        let base_oid = commit_file(&repo, "refs/heads/main", None, "a.txt", b"base\n");
        repo.reference("refs/heads/feature", base_oid, false, "create feature")
            .expect("create feature branch");

        let feature_oid = commit_file(
            &repo,
            "refs/heads/feature",
            Some(base_oid),
            "b.txt",
            b"feature change\n",
        );

        let result_sha = manager
            .merge_branches(
                "acme",
                "widgets",
                "feature",
                "main",
                "Merger",
                "merger@example.com",
                "Merge feature into main",
            )
            .expect("merge branches");

        assert_eq!(result_sha, feature_oid.to_string());

        let main_ref = repo
            .find_reference("refs/heads/main")
            .expect("find main ref");
        assert_eq!(main_ref.target().expect("target"), feature_oid);
    }

    #[test]
    fn merge_branches_creates_merge_commit_when_diverged() {
        let dir = tempfile::tempdir().expect("tempdir");
        let manager = RepoManager::new(dir.path());
        manager.init_repo("acme", "widgets").expect("init repo");
        let repo_path = manager.repo_path("acme", "widgets").expect("repo path");
        let repo = Repository::open_bare(&repo_path).expect("open bare repo");

        let base_oid = commit_file(&repo, "refs/heads/main", None, "a.txt", b"base\n");
        repo.reference("refs/heads/feature", base_oid, false, "create feature")
            .expect("create feature branch");

        // Diverge: commit on main and a different commit on feature.
        let main_oid = commit_file(
            &repo,
            "refs/heads/main",
            Some(base_oid),
            "main-only.txt",
            b"main change\n",
        );
        let feature_oid = commit_file(
            &repo,
            "refs/heads/feature",
            Some(base_oid),
            "feature-only.txt",
            b"feature change\n",
        );

        let result_sha = manager
            .merge_branches(
                "acme",
                "widgets",
                "feature",
                "main",
                "Merger",
                "merger@example.com",
                "Merge feature into main",
            )
            .expect("merge branches");

        let merge_commit = repo
            .find_commit(git2::Oid::from_str(&result_sha).expect("parse oid"))
            .expect("find merge commit");
        assert_eq!(merge_commit.parent_count(), 2);
        assert_eq!(merge_commit.parent_id(0).expect("parent0"), main_oid);
        assert_eq!(merge_commit.parent_id(1).expect("parent1"), feature_oid);

        let main_ref = repo
            .find_reference("refs/heads/main")
            .expect("find main ref");
        assert_eq!(main_ref.target().expect("target"), merge_commit.id());
    }

    #[test]
    fn wiki_write_read_and_update_page() {
        let dir = tempfile::tempdir().expect("tempdir");
        let manager = RepoManager::new(dir.path());
        manager.init_repo("acme", "widgets").expect("init repo");
        manager.init_wiki("acme", "widgets").expect("init wiki");

        let sha1 = manager
            .wiki_write_page(
                "acme",
                "widgets",
                "Home",
                "# Hello\n",
                "Test",
                "test@example.com",
                "create Home page",
            )
            .expect("write page");
        assert!(!sha1.is_empty());

        let pages = manager
            .wiki_list_pages("acme", "widgets")
            .expect("list pages");
        assert_eq!(pages, vec!["Home".to_string()]);

        let content = manager
            .wiki_read_page("acme", "widgets", "Home")
            .expect("read page");
        assert_eq!(content, "# Hello\n");

        let sha2 = manager
            .wiki_write_page(
                "acme",
                "widgets",
                "Home",
                "# Hello again\n",
                "Test",
                "test@example.com",
                "update Home page",
            )
            .expect("update page");
        assert_ne!(sha1, sha2);

        let content2 = manager
            .wiki_read_page("acme", "widgets", "Home")
            .expect("read updated page");
        assert_eq!(content2, "# Hello again\n");

        let pages2 = manager
            .wiki_list_pages("acme", "widgets")
            .expect("list pages again");
        assert_eq!(pages2, vec!["Home".to_string()]);
    }
}
