pub mod access_token;
pub mod activity_event;
pub mod branch_protection_rule;
pub mod dev_workspace;
pub mod issue;
pub mod issue_comment;
pub mod issue_label;
pub mod label;
pub mod milestone;
pub mod notification;
pub mod org_member;
pub mod organization;
pub mod pr_review;
pub mod pr_review_comment;
pub mod project;
pub mod project_card;
pub mod project_column;
pub mod pull_request;
pub mod repo_collaborator;
pub mod repo_secret;
pub mod repository;
pub mod ssh_key;
pub mod user;
pub mod webhook;
pub mod workflow_artifact;
pub mod workflow_job;
pub mod workflow_run;

pub mod prelude {
    pub use super::access_token::Entity as AccessToken;
    pub use super::activity_event::Entity as ActivityEvent;
    pub use super::branch_protection_rule::Entity as BranchProtectionRule;
    pub use super::dev_workspace::Entity as DevWorkspace;
    pub use super::issue::Entity as Issue;
    pub use super::issue_comment::Entity as IssueComment;
    pub use super::issue_label::Entity as IssueLabel;
    pub use super::label::Entity as Label;
    pub use super::milestone::Entity as Milestone;
    pub use super::notification::Entity as Notification;
    pub use super::org_member::Entity as OrgMember;
    pub use super::organization::Entity as Organization;
    pub use super::pr_review::Entity as PrReview;
    pub use super::pr_review_comment::Entity as PrReviewComment;
    pub use super::project::Entity as Project;
    pub use super::project_card::Entity as ProjectCard;
    pub use super::project_column::Entity as ProjectColumn;
    pub use super::pull_request::Entity as PullRequest;
    pub use super::repo_collaborator::Entity as RepoCollaborator;
    pub use super::repo_secret::Entity as RepoSecret;
    pub use super::repository::Entity as Repository;
    pub use super::ssh_key::Entity as SshKey;
    pub use super::user::Entity as User;
    pub use super::webhook::Entity as Webhook;
    pub use super::workflow_artifact::Entity as WorkflowArtifact;
    pub use super::workflow_job::Entity as WorkflowJob;
    pub use super::workflow_run::Entity as WorkflowRun;
}
